#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

catway_ensure_config
CLI_PATH="${CATWAY_CLI_PATH:-$CATWAY_PREFIX/bin/catway}"
YABAI="$(catway_yabai)"
KEYBOARD_ENABLED="$(catway_setting keyboardShortcuts true)"
SKETCHYBAR_ENABLED="$(catway_setting sketchyBarIntegration true)"
HIDE_EMPTY="$(catway_setting hideEmptyWorkspaces true)"
DISABLE_NATIVE="$(catway_setting disableNativeMissionControl true)"
FOUR_FINGER_GESTURES="$(catway_setting fourFingerGestures true)"
HORIZONTAL_GESTURE="$(catway_setting horizontalWorkspaceSwipe false)"
SHOW_EMPTY=true
[[ "$HIDE_EMPTY" == "true" ]] && SHOW_EMPTY=false

escape_sed() {
  printf '%s' "$1" | sed 's/[&|\\]/\\&/g'
}

render_template() {
  local source="$1"
  local destination="$2"
  shift 2
  local temporary expression key value
  temporary="$(mktemp "${destination}.XXXXXX")"
  cp "$source" "$temporary"
  while (( $# >= 2 )); do
    key="$1"
    value="$(escape_sed "$2")"
    shift 2
    expression="s|__${key}__|$value|g"
    sed -i '' "$expression" "$temporary"
  done
  chmod 0644 "$temporary"
  mv "$temporary" "$destination"
}

render_template \
  "$CATWAY_SHARE/integrations/hammerspoon/catway.lua.template" \
  "$CATWAY_CONFIG_HOME/hammerspoon.lua" \
  CATWAY_CLI "$CLI_PATH"

render_template \
  "$CATWAY_SHARE/integrations/yabai/catway.sh.template" \
  "$CATWAY_CONFIG_HOME/yabai.sh" \
  CATWAY_CLI "$CLI_PATH" \
  YABAI "$YABAI"

mkdir -p "$CATWAY_CONFIG_HOME/sketchybar"
for script in sync-spaces.sh space.sh remove-items.sh; do
  install -m 0755 "$CATWAY_SHARE/integrations/sketchybar/$script" "$CATWAY_CONFIG_HOME/sketchybar/$script"
done
install -m 0644 "$CATWAY_SHARE/assets/catway-process.png" "$CATWAY_CONFIG_HOME/sketchybar/catway-process.png"
if [[ ! -f "$CATWAY_CONFIG_HOME/sketchybar.local.sh" ]]; then
  install -m 0644 "$CATWAY_SHARE/integrations/sketchybar/sketchybar.local.example.sh" \
    "$CATWAY_CONFIG_HOME/sketchybar.local.sh"
fi
render_template \
  "$CATWAY_SHARE/integrations/sketchybar/sketchybarrc.template" \
  "$CATWAY_CONFIG_HOME/sketchybarrc" \
  CATWAY_CONFIG_HOME "$CATWAY_CONFIG_HOME" \
  CATWAY_CLI "$CLI_PATH" \
  SKETCHYBAR_ENABLED "$SKETCHYBAR_ENABLED" \
  SHOW_EMPTY "$SHOW_EMPTY"

SKHD_FILE="$CATWAY_CONFIG_HOME/catway.skhdrc"
SKHD_TEMP="$(mktemp "${SKHD_FILE}.XXXXXX")"
{
  printf '# Generated by Catway Settings. Your main skhdrc remains user-owned.\n'
  printf '# Set keyboardShortcuts to false to leave this file intentionally empty.\n'
  if [[ "$KEYBOARD_ENABLED" == "true" ]]; then
    printf '\n# Focus windows.\n'
    printf 'alt - h : "%s" -m window --focus west\n' "$YABAI"
    printf 'alt - j : "%s" -m window --focus south\n' "$YABAI"
    printf 'alt - k : "%s" -m window --focus north\n' "$YABAI"
    printf 'alt - l : "%s" -m window --focus east\n' "$YABAI"
    printf '\n# Move windows in the BSP tree.\n'
    printf 'shift + alt - h : "%s" -m window --warp west\n' "$YABAI"
    printf 'shift + alt - j : "%s" -m window --warp south\n' "$YABAI"
    printf 'shift + alt - k : "%s" -m window --warp north\n' "$YABAI"
    printf 'shift + alt - l : "%s" -m window --warp east\n' "$YABAI"
    printf '\n# Displays and split sizing.\n'
    printf 'ctrl + alt - h : "%s" -m window --display west --focus\n' "$YABAI"
    printf 'ctrl + alt - l : "%s" -m window --display east --focus\n' "$YABAI"
    printf 'alt - 0x1B : "%s" -m window --ratio rel:-0.05\n' "$YABAI"
    printf 'alt - 0x18 : "%s" -m window --ratio rel:0.05\n' "$YABAI"
    printf '\n# Option+/ cycles the focused window through tiled positions from any panel.\n'
    printf 'alt - 0x2C : "%s" rotate-windows\n' "$CLI_PATH"
    printf 'alt - 0x2B : "%s" -m space --layout stack\n' "$YABAI"
    printf '\n# Dynamic native workspaces. H/J/K/L stay directional.\n'
    for label in {1..9} {A..G} I {M..Z}; do
      key="$(printf '%s' "$label" | tr '[:upper:]' '[:lower:]')"
      printf 'alt - %s : "%s" workspace focus %s\n' "$key" "$CLI_PATH" "$label"
    done
    printf '\n'
    for label in {1..9} {A..G} I {M..Z}; do
      key="$(printf '%s' "$label" | tr '[:upper:]' '[:lower:]')"
      printf 'shift + alt - %s : "%s" workspace move %s\n' "$key" "$CLI_PATH" "$label"
    done
    printf '\n# Cycle through every active workspace.\n'
    printf 'alt - tab : "%s" focus next\n' "$CLI_PATH"
    printf 'shift + alt - tab : "%s" focus previous\n' "$CLI_PATH"
    printf '\n# Small service mode.\n'
    printf ':: catway\n'
    printf 'shift + alt - 0x29 ; catway\n'
    printf 'catway < escape ; default\n'
    printf 'catway < r : "%s" -m space --balance\n' "$YABAI"
    printf 'catway < f : "%s" -m window --toggle float\n' "$YABAI"
  fi
} > "$SKHD_TEMP"
chmod 0644 "$SKHD_TEMP"
mv "$SKHD_TEMP" "$SKHD_FILE"

PREFS_STATE="$CATWAY_STATE_DIR/native-mission-control.tsv"
touch "$PREFS_STATE"

snapshot_native_preference() {
  local domain="$1"
  local key="$2"
  local value
  if grep -Fq "${domain}"$'\t'"${key}"$'\t' "$PREFS_STATE"; then
    return 0
  fi
  if [[ "$domain" == "@currentHost:NSGlobalDomain" ]]; then
    value="$(defaults -currentHost read NSGlobalDomain "$key" 2>/dev/null || printf '__CATWAY_UNSET__')"
  else
    value="$(defaults read "$domain" "$key" 2>/dev/null || printf '__CATWAY_UNSET__')"
  fi
  printf '%s\t%s\t%s\n' "$domain" "$key" "$value" >> "$PREFS_STATE"
}

for pair in \
  'com.apple.dock showMissionControlGestureEnabled' \
  'com.apple.AppleMultitouchTrackpad TrackpadFourFingerVertSwipeGesture' \
  'com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerVertSwipeGesture' \
  'com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture' \
  'com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerHorizSwipeGesture' \
  '@currentHost:NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture' \
  '@currentHost:NSGlobalDomain com.apple.trackpad.fourFingerHorizSwipeGesture'
do
  snapshot_native_preference "${pair% *}" "${pair##* }"
done

restore_native_preference() {
  local requested_domain="$1"
  local requested_key="$2"
  local domain key value
  [[ -r "$PREFS_STATE" ]] || return 0
  while IFS=$'\t' read -r domain key value; do
    [[ "$domain" == "$requested_domain" && "$key" == "$requested_key" ]] || continue
    if [[ "$value" == "__CATWAY_UNSET__" ]]; then
      if [[ "$domain" == "@currentHost:NSGlobalDomain" ]]; then
        defaults -currentHost delete NSGlobalDomain "$key" >/dev/null 2>&1 || true
      else
        defaults delete "$domain" "$key" >/dev/null 2>&1 || true
      fi
    else
      if [[ "$domain" == "@currentHost:NSGlobalDomain" ]]; then
        defaults -currentHost write NSGlobalDomain "$key" -int "$value"
      else
        defaults write "$domain" "$key" -int "$value"
      fi
    fi
    return 0
  done < "$PREFS_STATE"
}

if [[ "$DISABLE_NATIVE" == "true" ]]; then
  defaults write com.apple.dock showMissionControlGestureEnabled -bool false
  defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerVertSwipeGesture -int 0
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerVertSwipeGesture -int 0
  defaults -currentHost write NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture -int 0
else
  restore_native_preference com.apple.dock showMissionControlGestureEnabled
  restore_native_preference com.apple.AppleMultitouchTrackpad TrackpadFourFingerVertSwipeGesture
  restore_native_preference com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerVertSwipeGesture
  restore_native_preference @currentHost:NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture
fi

if [[ "$FOUR_FINGER_GESTURES" == "true" && "$HORIZONTAL_GESTURE" == "true" ]]; then
  defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture -int 0
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerHorizSwipeGesture -int 0
  defaults -currentHost write NSGlobalDomain com.apple.trackpad.fourFingerHorizSwipeGesture -int 0
else
  restore_native_preference com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture
  restore_native_preference com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerHorizSwipeGesture
  restore_native_preference @currentHost:NSGlobalDomain com.apple.trackpad.fourFingerHorizSwipeGesture
fi

if SKHD="$(catway_find_executable skhd "${CATWAY_SKHD:-}" 2>/dev/null)"; then
  "$SKHD" --reload >/dev/null 2>&1 || true
fi
if "$YABAI" -m query --spaces >/dev/null 2>&1; then
  /bin/sh "$CATWAY_CONFIG_HOME/yabai.sh" >/dev/null 2>&1 || true
fi
if [[ "$SKETCHYBAR_ENABLED" == "true" ]]; then
  "$CATWAY_CONFIG_HOME/sketchybar/sync-spaces.sh" >/dev/null 2>&1 || true
else
  "$CATWAY_CONFIG_HOME/sketchybar/remove-items.sh" >/dev/null 2>&1 || true
fi

killall Dock >/dev/null 2>&1 || true
printf 'Catway settings applied.\n'
